version: "3.8"

services:
  api:
    build: .
    container_name: bazaar-api-container

    ports:
      - "3333:3333"

    env_file:
      - .env

    environment:
      # Redis local do compose
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""

      # Turso
      DATABASE_URL: libsql://bazaar-api-db-luizgustavolab.aws-us-west-2.turso.io

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - cache

  cache:
    image: redis:alpine
    container_name: bazaar-redis-cache

    ports:
      - "6379:6379"

    deploy:
      resources:
        limits:
          memory: 64M