version: "3.8"

services:
  api:
    build: .
    container_name: bazaar-api-container
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://cache:6379
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - .:/app
      - /app/node_modules # Protege os módulos internos do container
    depends_on:
      - cache

  cache:
    image: redis:alpine
    container_name: bazaar-redis-cache
    ports:
      - "6379:6379"
